[profile.default]
ffi = true
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 200
gas_reports = ["Registry", "Oracle"]
solc = "0.8.27"
test_pattern_exclude = "BLSTestingLib.t.sol"

remappings = [
    "forge-std/=lib/forge-std/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[profile.default.fuzz]
max_test_rejects = 1_000
runs = 10

[profile.ci]
optimizer = true
optimizer-runs = 200

[profile.ci.fuzz]
runs = 256

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4